* TCP/IP, 和OSI
UDP ， TCP 在传输层， IP 在网络层， TCP/IP 是英文 Transmission Control Protocol/Internet Protocol 的缩写，
意思是 " 传输控制协议 / 网际协议 " 。 TCP/IP 协议组之所以流行，部分原因是因为它可以用在各种各样的信道和底层协议（
例如 T1 和 X.25 、以太网以及 RS-232 串行接口）之上。
， TCP/IP 协议是一组包括 TCP 协议和 IP 协议， UDP （ User Datagram Protocol ）协议、 ICMP
 （ Internet Control Message Protocol ）协议和其他一些协议的协议组。
 TCP/IP 协议并不完全符合 OSI 的七层参考模型。
OSI传统的开放式系统互连参考模型，是一种通信协议的 7 层抽象的参考模型 , 其中每一层执行某一特定任务。该模型的目的是使各种硬件在
相同的层次上相互通信。这 7 层是 : 物理层、数据链路层、网路层、传输层、话路层、表示层和应用层。而 TCP/IP 通讯协议采用了 4 
层的层级结构，每一层都呼叫它的下一层所提供的网络来完成自己的需求。这 4 层分别为：
应用层 ：应用程序间沟通的层，如简单电子邮件传输（ SMTP ）、文件传输协议（ FTP ）、网络远程访问协议（ Telnet ）等。
传输层 ：在此层中，它提供了节点间的数据传送服务，如传输控制协议（ TCP ）、用户数据报协议（ UDP ）等， TCP 和 UDP 给数据包加入传输数据并把它传输到下一层中，这一层负责传送数据，并且确定数据已被送达并接收。
互连网络层 ：负责提供基本的数据封包传送功能，让每一块数据包都能够到达目的主机（但不检查是否被正确接收），如网际协议（ IP ）。
网络接口层 ：对实际的网络媒体的管理，定义如何使用实际网络（如 Ethernet 、 Serial Line 等）来传送数据。

* TCP 和UDP协议的区别
P协议是网络层的协议，它实现了Internet中自动路由的功能，即寻径的功能，TCP协议
是一个传输层的协议它向下屏蔽了IP协议不可靠传输的特性，向上提供一个可靠的点到点
的传输，UDP提供的是一种无连接的服务,主要考虑到很多应用不需要可靠的连接，但需要
快速的传输

Q3 ：请问交换机和路由器分别的实现原理是什么？分别在哪个层次上面实现的？
一般意义上说交换机是工作在数据链路层。但随着科技的发展，现在有了三层交换机，三层交换机已经扩展到了网络层。也就是说：它等于 “ 数据链路层 + 部分网络层 ” 。交换机中传的是帧。通过存储转发来实现的。 路由器是工作在网络层。路由器中传的是 IP 数据报。主要是选址和路由。 


* IP地址
保留地址的分配 
根据用途和安全性级别的不同，IP地址还可以大致分为两类：公共地址和私有地址。公用地址在Internet中使用，可以在Internet中随意访问。私有地址只能在内部网络中使用，只有通过代理服务器才能与Internet通信。 
公用IP地址被分为基本三类。
Class A 1.0.0.0-126.255.255.255
Class B 128.0.0.0-191.255.255.255
Class C 192.0.0.0 -255.255.255.255
这三个基本类决定了你可以拥有多少的次网络（subnets) 和连接多少的用户(devices)（服务器，网关，打印机，电脑等）
Class A 拥有3个host.
Class B 拥有2个host.
Class C 拥有1个host.

Class A 可以适用于超级大公司或者政府机关
Class B 可以适用于普通的集团公司或者学校
Class C 可以适用于一般公司

一个机构或网络要连入Internet，必须申请公用IP地址。但是考虑到网络安全和内部实验等特殊情况，
在IP地址中专门保留了三个区域作为私有地址，其地址范围如下： 
10.0.0.0/8：10.0.0.0～10.255.255.255 
172.16.0.0/12：172.16.0.0～172.31.255.255 
192.168.0.0/16：192.168.0.0～192.168.255.255 
使用保留地址的网络只能在内部进行通信，而不能与其他网络互连。因为本网络中的保留地址同样也可能被其他网络使用，
如果进行网络互连，那么寻找路由时就会因为地址的不唯一而出现问题。但是这些使用保留地址的网络可以通过将本网络内的
保留地址翻译转换成公共地址的方式实现与外部网络的互连。这也是保证网络安全的重要方法之一。
