* how to avoid DNS poisoning
Traditional way to bypass DNS poisoning is to send all queries to a foreign DNS server via VPN. However some Chinese websites will get bad results if they have CDNs outside the country.

The second way is to maintain a list of domains of which you want to resolve from local DNS or foreign DNS. This list changes too often, taking too much effort to maintain.


** ChinaDNS
ChinaDNS automatically queries local DNS servers to resolve Chinese domains and queries foreign DNS servers to resolve foreign domains. 
It is smart enough to work only with a Chinese IP range file, which doesn't change often.
*** get the chinese ip range file
-------------------------------------------------
RUN     curl 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | grep ipv4 | grep CN | awk -F\| '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > chnroute.txt \
    mv ./chnroute.txt /root/chnroute.txt
--------------------------------------------------

*** configure the dns server to use
 -c CHNROUTE_FILE      path to china route file if not specified, CHNRoute will be turned off
  -d                    enable bi-directional CHNRoute filter
  -y                    delay time for suspects, default: 0.3
  -b BIND_ADDR          address that listens, default: 127.0.0.1
  -p BIND_PORT          port that listens, default: 53
  -s DNS                DNS servers to use, default:
                        114.114.114.114,208.67.222.222:443,8.8.8.8
  -m                    Using DNS compression pointer mutation

114.114.114.114  -------------this is domestic dns server to use

8.8.8.8          -------------this is the foreign dns server to use, but gfw will drop the packet to 8.8.8.8, thus we need ss-tunnel to get 8.8.8.8
ss-tunnel -m  aes-128-cfb -k Willow_123 -s j0.0bad.com -p 31856 -l 5037 -b 192.168.31.75  -L 8.8.8.8:53 -u &
